version: "3"
services:
  bot:
    image: ewpratten/no-bitches-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LD_LIBRARY_PATH=/usr/local/lib
    command: /app